name: Provision Pipeline # Nome do pipeline, ainda não definido corretamente.

on:
  push:
    branches:
      - prod-v1.0 # Definir a branch que irá disparar o pipeline. 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # Criar os SECRETS AWS_ACCESS_KEY_ID e AWS_SECRET_ACCESS_KEY no repositório do GitHub.
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Validar e inserir a região que definir para utilização na AWS.
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: repositorio_generico # Criar e definir o repositorio ECS que será utilizado.
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
    - name: Fill in the new image ID in the ECS task definition
      id: render-task-definition
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: deploy/task-definition.json # Definir e informar o CAMINHO PARA O ARQUIVO JSON DE DEFINIÇÃO DA TAREFA.
        container-name: seu-container-django # Definir e substituir pelo NOME DO CONTÊINER NO SEU ARQUIVO task-definition.json.
        image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
        service: seu-servico-ecs # Definir e substituir pelo SERVIÇO ECS.
        cluster: seu-cluster-ecs # Definir e substituir pelo CLUSTER ECS.
        wait-for-service-stability: true
