---
name: Deploy - GCP

"on":
  workflow_dispatch:
    inputs:
      environment:
        description: >
          Target environment (ex.: prod, staging, dev)
        required: false
        default: "prod"
  push:
    branches:
      - "main"
    paths:
      - "infra/terraform/**"
      - ".github/workflows/deploy-gcp.yml"

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-gcp-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP via Workload Identity Federation
        if: ${{ secrets.GCP_WIF_PROVIDER != '' && secrets.GCP_SA_EMAIL != '' }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: >-
            ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: >-
            ${{ secrets.GCP_SA_EMAIL }}
          token_format: access_token

      - name: Auth to GCP via Service Account Key
        if: >-
          ${{ !(secrets.GCP_WIF_PROVIDER != '' && secrets.GCP_SA_EMAIL != '')
              && secrets.GCP_SA_KEY != '' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: >-
            ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Verify gcloud auth
        run: |
          set -euo pipefail
          gcloud auth list --filter=status:ACTIVE
          gcloud config list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Bootstrap - write tfvars
        working-directory: infra/terraform/bootstrap/gcp
        env:
          ENV_NAME: >-
            ${{ github.event.inputs.environment }}
          GCP_REGION: >-
            ${{ secrets.GCP_REGION }}
          GCP_PROJECT: >-
            ${{ secrets.GCP_PROJECT }}
        run: |
          set -euo pipefail
          env="${ENV_NAME:-prod}"
          project="${GCP_PROJECT:?missing GCP_PROJECT secret}"
          region="${GCP_REGION:-us-central1}"

          # Nome do bucket (sanitizado e com limite de 63 chars)
          bucket="${project}-tfstate-${env}"
          bucket="$(printf '%s' "$bucket" \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/[^a-z0-9-]/-/g' \
            | cut -c1-63)"

          printf 'project = "%s"\n' "$project" > terraform.tfvars
          printf 'region = "%s"\n' "$region" >> terraform.tfvars
          printf 'state_bucket_name = "%s"\n' "$bucket" >> terraform.tfvars

          echo "Wrote terraform.tfvars:"
          sed -n '1,120p' terraform.tfvars

      - name: Import existing state bucket if present
        working-directory: infra/terraform/bootstrap/gcp
        run: |
          set -euo pipefail

          if [ ! -f terraform.tfvars ]; then
            echo "terraform.tfvars not found; skipping import check"
            exit 0
          fi

          BUCKET=$(
            awk -F'"' \
              '/state_bucket_name/ {print $2; exit}' \
              terraform.tfvars || true
          )

          if [ -z "$BUCKET" ]; then
            echo "state_bucket_name not found in terraform.tfvars; skip"
            exit 0
          fi

          echo "Checking if bucket gs://$BUCKET exists..."
          if gsutil ls -b "gs://$BUCKET" >/dev/null 2>&1; then
            echo "Bucket exists — ensuring Terraform state is imported."
            terraform init -input=false

            if terraform state list \
              | grep -q '^google_storage_bucket\.terraform_state$'; then
              echo "google_storage_bucket.terraform_state already in state."
            else
              terraform import -lock=false \
                'google_storage_bucket.terraform_state' \
                "$BUCKET" || {
                  echo "terraform import failed"
                  terraform state list || true
                  exit 1
                }
            fi
          else
            echo "Bucket does not exist — Terraform will create it."
          fi

      - name: Bootstrap - init and apply
        working-directory: infra/terraform/bootstrap/gcp
        run: |
          set -euo pipefail
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Use TF_BUCKET from secret if provided
        env:
          TF_BUCKET_SECRET: ${{ secrets.TF_BUCKET }}
        run: |
          set -euo pipefail
          if [ -n "${TF_BUCKET_SECRET:-}" ]; then
            echo "TF_BUCKET=${TF_BUCKET_SECRET}" >> "$GITHUB_ENV"
            echo "Using TF_BUCKET from secret; skipping output parsing."
          else
            echo "No TF_BUCKET secret provided; will parse outputs."
          fi

      - name: Get bootstrap outputs - save JSON (robust)
        if: ${{ env.TF_BUCKET == '' }}
        working-directory: infra/terraform/bootstrap/gcp
        id: bootstrap
        run: |
          set -euo pipefail

          # Não usar -no-color aqui
          terraform output -json > /tmp/bootstrap.raw \
            2> /tmp/bootstrap.err || true

          if [ -s /tmp/bootstrap.err ]; then
            echo "NOTE: terraform wrote to stderr:"
            sed -n '1,200p' /tmp/bootstrap.err || true
          fi

          # Extrai o primeiro objeto JSON balanceado
          python - <<'PY' > /tmp/bootstrap.json \
            2> /tmp/bootstrap.py.err || true
          import sys, json
          s=open('/tmp/bootstrap.raw','r',errors='replace').read()
          i=s.find('{')
          if i==-1:
              sys.stderr.write('no JSON object start found\n'); sys.exit(2)
          depth=0
          end=-1
          for idx,ch in enumerate(s[i:], start=i):
              if ch=='{': depth+=1
              elif ch=='}': depth-=1
              if depth==0:
                  end=idx
                  break
          if end==-1:
              sys.stderr.write('no matching closing brace found\n'); sys.exit(3)
          js=s[i:end+1]
          try:
              obj=json.loads(js)
          except Exception as e:
              sys.stderr.write('json loads failed: %s\n' % e)
              sys.exit(4)
          sys.stdout.write(json.dumps(obj))
          PY

          if [ -s /tmp/bootstrap.py.err ]; then
            echo "ERROR: python extraction failed:"
            sed -n '1,200p' /tmp/bootstrap.py.err || true
            echo "--- raw terraform output ---"
            sed -n '1,200p' /tmp/bootstrap.raw || true
            exit 1
          fi

          if ! jq '.' /tmp/bootstrap.json >/dev/null 2>&1; then
            echo "ERROR: jq cannot parse /tmp/bootstrap.json"
            echo "--- cleaned text ---"
            sed -n '1,200p' /tmp/bootstrap.json || true
            exit 1
          fi

      - name: Export bootstrap outputs as env (robust)
        if: ${{ env.TF_BUCKET == '' }}
        working-directory: infra/terraform/bootstrap/gcp
        run: |
          set -euo pipefail
          if [ ! -s /tmp/bootstrap.json ]; then
            echo "ERROR: /tmp/bootstrap.json missing or empty"
            ls -l /tmp || true
            exit 1
          fi

          FILTER='
          (.state_bucket.value //
           .state_bucket_name.value //
           .state_bucket //
           .state_bucket_name //
           empty)
          '

          TF_BUCKET=$(jq -r "$FILTER" /tmp/bootstrap.json || true)

          if [ -z "$TF_BUCKET" ]; then
            echo "ERROR: could not determine TF_BUCKET from outputs."
            echo "Expected 'state_bucket' or 'state_bucket_name' outputs."
            echo "Available keys are:"
            jq -r 'keys[]' /tmp/bootstrap.json || true
            exit 6
          fi

          echo "TF_BUCKET=$TF_BUCKET" >> "$GITHUB_ENV"
          echo "Exported TF_BUCKET=$TF_BUCKET"

      - name: Write backend.hcl for GCP infra
        env:
          TF_BUCKET: ${{ env.TF_BUCKET }}
          ENV_NAME: >-
            ${{ github.event.inputs.environment }}
        run: |
          set -euo pipefail
          mkdir -p infra/terraform/gcp
          env="${ENV_NAME:-prod}"
          printf 'bucket = "%s"\n' "$TF_BUCKET" \
            > infra/terraform/gcp/backend.hcl
          printf 'prefix = "%s"\n' "env/${env}" \
            >> infra/terraform/gcp/backend.hcl
          echo "backend.hcl:"
          sed -n '1,120p' infra/terraform/gcp/backend.hcl

      - name: Terraform init (gcp infra)
        working-directory: infra/terraform/gcp
        run: |
          set -euo pipefail
          terraform init -backend-config=backend.hcl \
            -reconfigure -input=false

      - name: Terraform apply (gcp infra)
        working-directory: infra/terraform/gcp
        run: |
          set -euo pipefail
          terraform apply -auto-approve -input=false

      - name: Output results (JSON)
        if: success()
        working-directory: infra/terraform/gcp
        run: |
          set -euo pipefail
          terraform output -json || true

      - name: Done
        run: echo "Deploy GCP finished."
