---
name: Provision App CI/CD to Cloud Run

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'gcp-deploy'

# Configurações globais usando seus secrets e vars
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  SERVICE_NAME: provision-app
  WIF_SA_EMAIL: ${{ vars.GCP_SA_EMAIL }}
  TF_STATE_BUCKET: tf-state-provision-bucket

jobs:
  # ---------------------------------------------------------------------
  # 1. INFRASTRUCTURE
  # ---------------------------------------------------------------------
  infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Google Auth (Workload Identity)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # CORREÇÃO: Usa o Secret que contém o ID limpo e completo do WIF para evitar a duplicação
          workload_identity_provider: ${{ secrets.GCP_WIF_AUDIENCE_ID }}
          service_account: ${{ env.WIF_SA_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ steps.auth.outputs.access_token }}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}"
        working-directory: infra/gcp

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -json
        working-directory: infra/gcp
        env:
          TF_VAR_gcp_project_id: ${{ env.GCP_PROJECT_ID }}
          TF_VAR_gcp_region: ${{ env.GCP_REGION }}
          TF_VAR_app_name: ${{ env.SERVICE_NAME }}

      - name: Get Terraform Outputs
        id: outputs
        run: |
          BUCKET_NAME=$(terraform output -raw gcs_bucket_name)
          echo "GCS_BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
        working-directory: infra/gcp

  # ---------------------------------------------------------------------
  # 2. BUILD
  # ---------------------------------------------------------------------
  build:
    needs: [infrastructure]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Google Auth (Workload Identity)
        id: auth-build
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_AUDIENCE_ID }}
          service_account: ${{ env.WIF_SA_EMAIL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}-repo/${{ env.SERVICE_NAME }}:latest

  # ---------------------------------------------------------------------
  # 3. DEPLOY
  # ---------------------------------------------------------------------
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Google Auth (Workload Identity)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_AUDIENCE_ID }}
          service_account: ${{ env.WIF_SA_EMAIL }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.GCP_REGION }}
          image: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}-repo/${{ env.SERVICE_NAME }}:latest
