---
name: Deploy - GCP

on:
  workflow_dispatch:
    inputs:
      environment:
        description: >
          Target environment (ex.: prod, staging, dev)
        required: false
        default: prod
  push:
    branches:
      - main
    paths:
      - infra/terraform/**
      - .github/workflows/deploy-gcp.yml

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-gcp-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      # Somente estas duas são Variáveis (Settings > Variables)
      GCP_WIF_PROVIDER: ${{ vars.GCP_WIF_PROVIDER }}
      GCP_SA_EMAIL: ${{ vars.GCP_SA_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validar variáveis necessárias (WIF)
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${GCP_WIF_PROVIDER:-}" ] || \
             [ -z "${GCP_SA_EMAIL:-}" ]; then
            echo "Missing required repository variables:"
            echo " - GCP_WIF_PROVIDER"
            echo " - GCP_SA_EMAIL"
            echo "Configure em Settings > Variables."
            exit 1
          fi

      - name: Autenticar via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.GCP_SA_EMAIL }}
          token_format: access_token

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Verificar auth gcloud
        shell: bash
        run: |
          set -euo pipefail
          gcloud auth list --filter=status:ACTIVE
          gcloud config list

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Bootstrap - escrever tfvars
        working-directory: infra/terraform/bootstrap/gcp
        env:
          ENV_NAME: ${{ github.event.inputs.environment }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
        shell: bash
        run: |
          set -euo pipefail
          env_name="${ENV_NAME:-prod}"
          project="${GCP_PROJECT:?missing secret GCP_PROJECT}"
          region="${GCP_REGION:-us-central1}"

          bucket="${project}-tfstate-${env_name}"
          bucket="$(printf '%s' "$bucket" \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/[^a-z0-9-]/-/g' \
            | cut -c1-63)"

          {
            printf 'project = "%s"\n' "$project"
            printf 'region = "%s"\n' "$region"
            printf 'state_bucket_name = "%s"\n' "$bucket"
          } > terraform.tfvars

          echo "Wrote terraform.tfvars:"
          sed -n '1,120p' terraform.tfvars

      - name: Importar bucket existente (se houver)
        working-directory: infra/terraform/bootstrap/gcp
        shell: bash
        run: |
          set -euo pipefail

          if [ ! -f terraform.tfvars ]; then
            echo "terraform.tfvars não encontrado; pulando import"
            exit 0
          fi

          BUCKET="$(
            awk -F '"' '/state_bucket_name/ {print $2; exit}' \
              terraform.tfvars || true
          )"

          if [ -z "$BUCKET" ]; then
            echo "state_bucket_name ausente; pulando import"
            exit 0
          fi

          echo "Checando gs://$BUCKET ..."
          if gsutil ls -b "gs://$BUCKET" >/dev/null 2>&1; then
            echo "Bucket existe; importando no state (se necessário)."
            terraform init -input=false

            if terraform state list | \
              grep -q '^google_storage_bucket\.terraform_state$'
            then
              echo "Recurso já no state; pulando import."
            else
              terraform import -lock=false \
                'google_storage_bucket.terraform_state' \
                "$BUCKET" || {
                  echo "terraform import falhou"
                  terraform state list || true
                  exit 1
                }
            fi
          else
            echo "Bucket não existe; Terraform irá criar."
          fi

      - name: Bootstrap - init e apply
        working-directory: infra/terraform/bootstrap/gcp
        shell: bash
        run: |
          set -euo pipefail
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Determinar TF_BUCKET (secret > output > tfvars)
        working-directory: infra/terraform/bootstrap/gcp
        env:
          TF_BUCKET_SECRET: ${{ secrets.TF_BUCKET }}
        shell: bash
        run: |
          set -euo pipefail
          TF_BUCKET=""

          if [ -n "${TF_BUCKET_SECRET:-}" ]; then
            TF_BUCKET="${TF_BUCKET_SECRET}"
            echo "Usando TF_BUCKET do secret."
          fi

          if [ -z "$TF_BUCKET" ]; then
            TF_BUCKET="$(
              terraform output -raw state_bucket 2>/dev/null || true
            )"
          fi
          if [ -z "$TF_BUCKET" ]; then
            TF_BUCKET="$(
              terraform output -raw state_bucket_name 2>/dev/null || true
            )"
          fi

          if [ -z "$TF_BUCKET" ] && [ -f terraform.tfvars ]; then
            TF_BUCKET="$(
              awk -F '"' '/state_bucket_name/ {print $2; exit}' \
                terraform.tfvars || true
            )"
          fi

          if [ -z "$TF_BUCKET" ]; then
            echo "ERROR: não foi possível determinar TF_BUCKET."
            echo "Forneça o secret TF_BUCKET ou garanta que o"
            echo "bootstrap exporta 'state_bucket'/'state_bucket_name'."
            exit 6
          fi

          echo "TF_BUCKET=${TF_BUCKET}" >> "$GITHUB_ENV"
          echo "TF_BUCKET resolvido: ${TF_BUCKET}"

      - name: Escrever backend.hcl (infra GCP)
        env:
          ENV_NAME: ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p infra/terraform/gcp
          env_name="${ENV_NAME:-prod}"
          {
            printf 'bucket = "%s"\n' "$TF_BUCKET"
            printf 'prefix = "%s"\n' "env/${env_name}"
          } > infra/terraform/gcp/backend.hcl
          echo "backend.hcl:"
          sed -n '1,120p' infra/terraform/gcp/backend.hcl

      - name: Terraform init (infra gcp)
        working-directory: infra/terraform/gcp
        shell: bash
        run: |
          set -euo pipefail
          terraform init -backend-config=backend.hcl \
            -reconfigure -input=false

      - name: Terraform apply (infra gcp)
        working-directory: infra/terraform/gcp
        shell: bash
        run: |
          set -euo pipefail
          terraform apply -auto-approve -input=false

      - name: Outputs (JSON)
        if: success()
        working-directory: infra/terraform/gcp
        shell: bash
        run: |
          set -euo pipefail
          terraform output -json || true

      - name: Done
        shell: bash
        run: echo "Deploy GCP finished."
