---
name: Deploy GCP infra

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: prod

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check required GCP secret
        run: |
          set -euo pipefail
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "ERROR: missing secret GCP_SA_KEY"
            exit 1
          fi

  deploy-gcp:
    runs-on: ubuntu-latest
    needs: validate
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Bootstrap - write tfvars
        working-directory: terraform/bootstrap/gcp
        env:
          ENV_NAME: ${{ github.event.inputs.environment }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
        run: |
          set -euo pipefail
          env="${ENV_NAME:-prod}"
          printf 'environment = "%s"\n' "$env" > terraform.tfvars
          printf 'gcp_region = "%s"\n' "$GCP_REGION" >> terraform.tfvars

      - name: Bootstrap - init and apply
        working-directory: terraform/bootstrap/gcp
        run: |
          set -euo pipefail
          terraform init -input=false
          terraform apply -auto-approve -input=false

      - name: Get bootstrap outputs - save JSON
        working-directory: terraform/bootstrap/gcp
        id: bootstrap
        run: |
          set -euo pipefail
          terraform output -json > /tmp/bootstrap.json

      - name: Export bootstrap outputs as env
        run: |
          set -euo pipefail
          TF_BUCKET=$(jq -r '.state_bucket.value' /tmp/bootstrap.json)
          printf 'TF_BUCKET=%s\n' "$TF_BUCKET" >> $GITHUB_ENV
        env:
          GCP_REGION: ${{ secrets.GCP_REGION }}
          ENV_NAME: ${{ github.event.inputs.environment }}

      - name: Write backend.hcl for GCP infra
        env:
          TF_BUCKET: ${{ env.TF_BUCKET }}
          ENV_NAME: ${{ github.event.inputs.environment }}
        run: |
          set -euo pipefail
          mkdir -p infra/terraform/gcp
          env="${ENV_NAME:-prod}"
          printf 'bucket = "%s"\n' "$TF_BUCKET" \
            > infra/terraform/gcp/backend.hcl
          printf 'prefix = "%s"\n' "env/${env}" \
            >> infra/terraform/gcp/backend.hcl
          sed -n '1,120p' infra/terraform/gcp/backend.hcl

      - name: Terraform init (gcp infra)
        working-directory: infra/terraform/gcp
        run: |
          set -euo pipefail
          terraform init -backend-config=backend.hcl -reconfigure -input=false

      - name: Terraform apply (gcp infra)
        working-directory: infra/terraform/gcp
        run: |
          set -euo pipefail
          terraform apply -auto-approve -input=false

      - name: Output results
        if: success()
        working-directory: infra/terraform/gcp
        run: terraform output -json
