name: Terraform force-unlock

on:
  workflow_dispatch:

jobs:
  force-unlock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Write backend.hcl
        run: |
          mkdir -p infra/terraform/gcp
          cat > infra/terraform/gcp/backend.hcl <<EOF
          bucket         = "${{ secrets.TF_STATE_BUCKET }}"
          key            = "${{ secrets.TF_STATE_KEY }}"
          region         = "${{ secrets.AWS_REGION }}"
          dynamodb_table = "${{ secrets.TF_DDB_TABLE }}"
          EOF

      - name: Init & Force-unlock
        working-directory: infra/terraform
        run: |
          set -euo pipefail
          terraform init -backend-config=backend.hcl -reconfigure -input=false
          terraform force-unlock -force 483b6026-fb2a-97bb-82b8-7e771d06968c
