name: Terraform force-unlock

on:
  workflow_dispatch:

jobs:
  force-unlock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Force unlock Terraform state
        run: |
          set -euo pipefail
          # Ajuste este caminho para onde seu backend/terraform root está no repositório
          cd infra/terraform/gcp || cd .
          terraform init -input=false
          terraform force-unlock -force 483b6026-fb2a-97bb-82b8-7e771d06968c
