name: Infra - Terraform

on:
  pull_request:
    paths:
      - 'infra/terraform/**'
  push:
    branches:
      - infra/main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init (PR safe)
      working-directory: infra/terraform
      run: terraform init -input=false -backend=false

    - name: Terraform Format
      working-directory: infra/terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: infra/terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: infra/terraform
      env:
        TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      run: |
        terraform plan -out=tfplan -input=false \
          -var="environment=pr-${{ github.run_id }}" \
          || true
    # opcional: publicar o plan como artefato ou como comentário do PR