on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        working-directory: infra/terraform
        run: terraform init -input=false

      - name: Terraform plan
        working-directory: infra/terraform
        run: terraform plan -input=false -out=tfplan

      - name: Terraform apply
        id: apply
        working-directory: infra/terraform
        run: terraform apply -input=false -auto-approve tfplan

      - name: Get instance_id output
        working-directory: infra/terraform
        run: |
          terraform output -json > /tmp/tf_outputs.json
          cat /tmp/tf_outputs.json
          jq -r '.instance_id.value' /tmp/tf_outputs.json > /tmp/instance_id.txt
          echo "::set-output name=instance_id::$(cat /tmp/instance_id.txt)"